name: movieshub
description: A MovieHub Flutter project
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  # HTTP for TMDB API
  http: ^1.2.1

  # YouTube Trailer Player
  youtube_player_flutter: ^9.1.3

  # Button package
  reactive_button: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/image.png"
