// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRrxJ3Fx-OIHv8oKQa3XssLIFexiCzmg',
    appId: '1:62072707246:web:804b11490b3c9f26b4353f',
    messagingSenderId: '62072707246',
    projectId: 'instagram-mini-6ccfa',
    authDomain: 'instagram-mini-6ccfa.firebaseapp.com',
    storageBucket: 'instagram-mini-6ccfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyHtD7xqAgNGAquF-WK6HFAwuyLv6_Fmk',
    appId: '1:62072707246:android:e6f96b3ba93ef4b4b4353f',
    messagingSenderId: '62072707246',
    projectId: 'instagram-mini-6ccfa',
    storageBucket: 'instagram-mini-6ccfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuMQlTRciVA2ytkdAgtjhTMVMCSukeK0',
    appId: '1:62072707246:ios:6bdf242385774950b4353f',
    messagingSenderId: '62072707246',
    projectId: 'instagram-mini-6ccfa',
    storageBucket: 'instagram-mini-6ccfa.firebasestorage.app',
    iosBundleId: 'com.example.movieshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuMQlTRciVA2ytkdAgtjhTMVMCSukeK0',
    appId: '1:62072707246:ios:6bdf242385774950b4353f',
    messagingSenderId: '62072707246',
    projectId: 'instagram-mini-6ccfa',
    storageBucket: 'instagram-mini-6ccfa.firebasestorage.app',
    iosBundleId: 'com.example.movieshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJRrxJ3Fx-OIHv8oKQa3XssLIFexiCzmg',
    appId: '1:62072707246:web:0da9cc79b1206f54b4353f',
    messagingSenderId: '62072707246',
    projectId: 'instagram-mini-6ccfa',
    authDomain: 'instagram-mini-6ccfa.firebaseapp.com',
    storageBucket: 'instagram-mini-6ccfa.firebasestorage.app',
  );
}
